# -*- coding: utf-8 -*-
"""Copy of ASSET RISK ENGINE

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PFB1EO4NUzkuhhHQNmpmVItzgRNonwP1
"""

import pandas as pd
import numpy as np

from google.colab import files

uploaded = files.upload()

import zipfile
import os

zip_path = "/content/CMAPSSData.zip"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall("/content/cmapss")

for root, dirs, files in os.walk("/content/cmapss"):
    for file in files:
        print(os.path.join(root, file))

train_path = "/content/cmapss/train_FD001.txt"
test_path = "/content/cmapss/test_FD001.txt"
rul_path = "/content/cmapss/RUL_FD001.txt"

train_df = pd.read_csv(train_path, sep=r"\s+", header=None)

print(train_df.shape)
display(train_df.head())

print(train_df.shape)

print(train_df.columns.tolist())

display(train_df.head())

columns = [
    'engine_id',
    'cycle',
    'setting1',
    'setting2',
    'setting3',
    'sensor1',
    'sensor2',
    'sensor3',
    'sensor4',
    'sensor5',
    'sensor6',
    'sensor7',
    'sensor8',
    'sensor9',
    'sensor10',
    'sensor11',
    'sensor12',
    'sensor13',
    'sensor14',
    'sensor15',
    'sensor16',
    'sensor17',
    'sensor18',
    'sensor19',
    'sensor20',
    'sensor21'
]

train_df.columns = columns

display(train_df.head())

max_cycle = train_df.groupby('engine_id')['cycle'].max()

train_df['RUL'] = train_df.apply(
    lambda row: max_cycle[row['engine_id']] - row['cycle'],
    axis=1
)

display(train_df[['engine_id', 'cycle', 'RUL']].head(10))

def rul_to_risk(rul):

    if rul <= 20:
        return "High"

    elif rul <= 50:
        return "Medium"

    else:
        return "Low"

print(train_df['RUL'].describe())

print(train_df['engine_id'].nunique())

train_df[['cycle', 'RUL']].head(20)

features = [
    'sensor1',
    'sensor2',
    'sensor3',
    'sensor4',
    'sensor5',
    'sensor6',
    'sensor7',
    'sensor8',
    'sensor9',
    'sensor10',
    'sensor11',
    'sensor12',
    'sensor13',
    'sensor14',
    'sensor15',
    'sensor16',
    'sensor17',
    'sensor18',
    'sensor19',
    'sensor20',
    'sensor21'
]

X = train_df[features]
y = train_df['RUL']

print("X:", X.shape)
print("y:", y.shape)

engines = train_df['engine_id'].unique()

split = int(len(engines) * 0.8)

train_engines = engines[:split]
test_engines = engines[split:]

train_data = train_df[
    train_df['engine_id'].isin(train_engines)
]

test_data = train_df[
    train_df['engine_id'].isin(test_engines)
]

print("Train engines:", len(train_engines))
print("Test engines:", len(test_engines))
print("Train rows:", len(train_data))
print("Test rows:", len(test_data))

X_train = train_data[features]
y_train = train_data['RUL']

X_test = test_data[features]
y_test = test_data['RUL']

from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

mae = mean_absolute_error(y_test, y_pred)

rmse = np.sqrt(
    mean_squared_error(y_test, y_pred)
)

print("MAE:", mae)
print("RMSE:", rmse)

def rul_to_risk(rul):
    if rul <= 20:
        return "High"
    elif rul <= 50:
        return "Medium"
    else:
        return "Low"

test_data = test_data.copy()

test_data['Predicted_RUL'] = y_pred

test_data['Risk'] = test_data['Predicted_RUL'].apply(rul_to_risk)

test_data[['engine_id', 'cycle', 'Predicted_RUL', 'Risk']].head(20)

test_data['Risk'].value_counts()

import numpy as np

# Simple baseline:
# predict the average RUL from the training data
baseline_prediction = y_train.mean()

baseline_pred = np.full(len(y_test), baseline_prediction)

print("Baseline predicted RUL:", baseline_prediction)

from sklearn.metrics import mean_absolute_error, mean_squared_error

baseline_mae = mean_absolute_error(y_test, baseline_pred)
baseline_rmse = np.sqrt(mean_squared_error(y_test, baseline_pred))

print("Baseline MAE:", baseline_mae)
print("Baseline RMSE:", baseline_rmse)

def get_risk_reason(rul):
    if rul <= 20:
        return "Very low estimated remaining useful life"
    elif rul <= 50:
        return "Low estimated remaining useful life"
    else:
        return "Sufficient estimated remaining useful life"

test_data['Reason'] = test_data['Predicted_RUL'].apply(get_risk_reason)

test_data[
    ['engine_id', 'cycle', 'Predicted_RUL', 'Risk', 'Reason']
].head(20)

risk_summary = test_data[
    ['engine_id', 'cycle', 'Predicted_RUL', 'Risk', 'Reason']
].copy()

risk_summary.head(20)

high_risk = test_data[
    test_data['Risk'] == 'High'
].sort_values('Predicted_RUL')

high_risk[
    ['engine_id', 'cycle', 'Predicted_RUL', 'Risk', 'Reason']
].head(20)

import pandas as pd

importance = pd.DataFrame({
    'Feature': features,
    'Importance': model.feature_importances_
})

importance = importance.sort_values(
    'Importance',
    ascending=False
)

importance

importance.head(10)

import matplotlib.pyplot as plt

importance.head(10).plot(
    x='Feature',
    y='Importance',
    kind='bar',
    figsize=(10, 5)
)

plt.title('Top 10 Features for RUL Prediction')
plt.ylabel('Importance')
plt.xlabel('Sensor')
plt.xticks(rotation=45)
plt.show()

import os

print(os.listdir('/content'))

from google.colab import files

uploaded = files.upload()

import zipfile
import os

zip_name = list(uploaded.keys())[0]

with zipfile.ZipFile(zip_name, 'r') as zip_ref:
    zip_ref.extractall('/content/cmapss')

print(os.listdir('/content/cmapss'))

import os

for root, dirs, files_list in os.walk('/content/cmapss'):
    for file in files_list:
        print(os.path.join(root, file))

import pandas as pd

columns = [
    'engine_id',
    'cycle',
    'setting1',
    'setting2',
    'setting3',
    'sensor1',
    'sensor2',
    'sensor3',
    'sensor4',
    'sensor5',
    'sensor6',
    'sensor7',
    'sensor8',
    'sensor9',
    'sensor10',
    'sensor11',
    'sensor12',
    'sensor13',
    'sensor14',
    'sensor15',
    'sensor16',
    'sensor17',
    'sensor18',
    'sensor19',
    'sensor20',
    'sensor21'
]

test_raw = pd.read_csv(
    '/content/cmapss/test_FD001.txt',
    sep=r'\s+',
    header=None
)

test_raw = test_raw.dropna(axis=1, how='all')
test_raw.columns = columns

print(test_raw.shape)
test_raw.head()

true_rul = pd.read_csv(
    '/content/cmapss/RUL_FD001.txt',
    header=None
)

true_rul.columns = ['RUL']

print(true_rul.shape)
true_rul.head()

print("Number of test engines:", test_raw['engine_id'].nunique())
print("Number of RUL values:", len(true_rul))

import pandas as pd
from sklearn.ensemble import RandomForestRegressor

# Define features (sensor columns) - Already present from previous fix
features = [
    'sensor1',
    'sensor2',
    'sensor3',
    'sensor4',
    'sensor5',
    'sensor6',
    'sensor7',
    'sensor8',
    'sensor9',
    'sensor10',
    'sensor11',
    'sensor12',
    'sensor13',
    'sensor14',
    'sensor15',
    'sensor16',
    'sensor17',
    'sensor18',
    'sensor19',
    'sensor20',
    'sensor21'
]

# Define columns for the dataframes - Already present from previous fix for test_raw
columns = [
    'engine_id',
    'cycle',
    'setting1',
    'setting2',
    'setting3',
    'sensor1',
    'sensor2',
    'sensor3',
    'sensor4',
    'sensor5',
    'sensor6',
    'sensor7',
    'sensor8',
    'sensor9',
    'sensor10',
    'sensor11',
    'sensor12',
    'sensor13',
    'sensor14',
    'sensor15',
    'sensor16',
    'sensor17',
    'sensor18',
    'sensor19',
    'sensor20',
    'sensor21'
]

# --- Start: Code to define and train the model ---

# Load training data
train_path = "/content/cmapss/train_FD001.txt"
train_df = pd.read_csv(train_path, sep=r"\s+", header=None)
train_df.columns = columns

# Calculate RUL for training data
max_cycle = train_df.groupby('engine_id')['cycle'].max()
train_df['RUL'] = train_df.apply(
    lambda row: max_cycle[row['engine_id']] - row['cycle'],
    axis=1
)

# Split training data (using 80/20 engine split for consistency with previous cells)
engines = train_df['engine_id'].unique()
split = int(len(engines) * 0.8)
train_engines = engines[:split]

train_data = train_df[
    train_df['engine_id'].isin(train_engines)
]

# Prepare X_train and y_train
X_train = train_data[features]
y_train = train_data['RUL']

# Define and train the RandomForestRegressor model
model = RandomForestRegressor(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)
model.fit(X_train, y_train)

# --- End: Code to define and train the model ---

# Predict RUL for the official test set
X_official = test_raw[features]

official_pred = model.predict(X_official)

test_raw['Predicted_RUL'] = official_pred

test_raw.head()

# Get the last recorded cycle for each engine

last_cycles = (
    test_raw
    .sort_values(['engine_id', 'cycle'])
    .groupby('engine_id')
    .tail(1)
    .sort_values('engine_id')
)

last_cycles[['engine_id', 'cycle', 'Predicted_RUL']].head(10)

# Add true RUL

last_cycles = last_cycles.reset_index(drop=True)

last_cycles['True_RUL'] = true_rul['RUL']

last_cycles.head(10)

from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

mae_official = mean_absolute_error(
    last_cycles['True_RUL'],
    last_cycles['Predicted_RUL']
)

rmse_official = np.sqrt(
    mean_squared_error(
        last_cycles['True_RUL'],
        last_cycles['Predicted_RUL']
    )
)

print("Official MAE:", mae_official)
print("Official RMSE:", rmse_official)

def rul_to_risk(rul):
    if rul <= 20:
        return "High"
    elif rul <= 50:
        return "Medium"
    else:
        return "Low"

last_cycles['Risk'] = last_cycles['Predicted_RUL'].apply(rul_to_risk)

last_cycles[['engine_id', 'cycle', 'True_RUL',
             'Predicted_RUL', 'Risk']].head(20)

last_cycles['Risk'].value_counts()

last_cycles[['True_RUL', 'Predicted_RUL']].describe()

pd.crosstab(
    pd.cut(
        last_cycles['True_RUL'],
        bins=[-1, 20, 50, float('inf')],
        labels=['High', 'Medium', 'Low']
    ),
    last_cycles['Risk']
)

last_cycles[['engine_id', 'True_RUL', 'Predicted_RUL', 'Risk']].sort_values(
    'True_RUL'
).head(30)

last_cycles[['engine_id', 'True_RUL', 'Predicted_RUL', 'Risk']].sort_values(
    'Predicted_RUL'
).head(30)

importance_df = pd.DataFrame({
    'Feature': features,
    'Importance': model.feature_importances_
}).sort_values('Importance', ascending=False)

importance_df

importance_df.head(10)

import joblib

joblib.dump(model, '/content/rul_random_forest.pkl')

print("Model saved successfully!")

import json

with open('/content/features.json', 'w') as f:
    json.dump(features, f)

print(features)

def predict_risk(sensor_data):

    predicted_rul = rf_model.predict(sensor_data[features])[0]

    if predicted_rul <= 20:
        risk = "High"
        reason = "Very low estimated remaining useful life"
    elif predicted_rul <= 50:
        risk = "Medium"
        reason = "Low estimated remaining useful life"
    else:
        risk = "Low"
        reason = "Sufficient estimated remaining useful life"

    return {
        "predicted_rul": round(float(predicted_rul), 2),
        "risk": risk,
        "reason": reason
    }

def predict_risk(sensor_data):

    predicted_rul = model.predict(sensor_data[features])[0]

    if predicted_rul <= 20:
        risk = "High"
        reason = "Very low estimated remaining useful life"
    elif predicted_rul <= 50:
        risk = "Medium"
        reason = "Low estimated remaining useful life"
    else:
        risk = "Low"
        reason = "Sufficient estimated remaining useful life"

    return {
        "predicted_rul": round(float(predicted_rul), 2),
        "risk": risk,
        "reason": reason
    }

sample = test_raw[features].iloc[[0]]

result = predict_risk(sample)

result

import os

print(os.path.exists('/content/rul_random_forest.pkl'))
print(os.path.exists('/content/features.json'))

from google.colab import files

files.download('/content/rul_random_forest.pkl')
files.download('/content/features.json')

def predict_asset(sensor_data):
    """
    Predict RUL and maintenance risk for one asset.
    """

    # Predict RUL
    predicted_rul = rf_model.predict(sensor_data[features])[0]

    # Convert RUL to risk
    if predicted_rul <= 20:
        risk = "High"
        reason = "Very low estimated remaining useful life"

    elif predicted_rul <= 50:
        risk = "Medium"
        reason = "Low estimated remaining useful life"

    else:
        risk = "Low"
        reason = "Sufficient estimated remaining useful life"

    return {
        "predicted_rul": round(float(predicted_rul), 2),
        "risk": risk,
        "reason": reason
    }

def predict_asset(sensor_data):
    """
    Predict RUL and maintenance risk for one asset.
    """

    # Predict RUL
    predicted_rul = model.predict(sensor_data[features])[0]

    # Convert RUL to risk
    if predicted_rul <= 20:
        risk = "High"
        reason = "Very low estimated remaining useful life"

    elif predicted_rul <= 50:
        risk = "Medium"
        reason = "Low estimated remaining useful life"

    else:
        risk = "Low"
        reason = "Sufficient estimated remaining useful life"

    return {
        "predicted_rul": round(float(predicted_rul), 2),
        "risk": risk,
        "reason": reason
    }

sample_assets = test_raw[features].iloc[:10]

results = []

for i in range(len(sample_assets)):
    result = predict_asset(sample_assets.iloc[[i]])
    result["engine_id"] = int(test_raw.iloc[i]["engine_id"])
    results.append(result)

results_df = pd.DataFrame(results)

results_df

ai_documentation = """
# AI Predictive Maintenance Model

## 1. Model
Random Forest Regressor

## 2. Dataset
NASA C-MAPSS FD001

## 3. Target
Remaining Useful Life (RUL)

## 4. Input Features
sensor1
sensor2
sensor3
sensor4
sensor5
sensor6
sensor7
sensor8
sensor9
sensor10
sensor11
sensor12
sensor13
sensor14
sensor15
sensor16
sensor17
sensor18
sensor19
sensor20
sensor21

## 5. Official Evaluation
MAE: 23.33 cycles
RMSE: 31.30 cycles

## 6. Baseline
Baseline MAE: 64.09 cycles

## 7. Risk Mapping
RUL <= 20  -> High
RUL <= 50  -> Medium
RUL > 50   -> Low

Note:
The risk thresholds are experimental thresholds used for this ML experiment.
They are not defined as official thresholds in the project requirements.

## 8. Explainability
Feature importance was used to identify which sensors contributed most
to the Random Forest predictions.

Top features:
- sensor11: 0.454216
- sensor9: 0.128539
- sensor4: 0.082643
- sensor12: 0.048335
- sensor14: 0.038919

## 9. Output
The prediction pipeline returns:
- predicted_rul
- risk
- reason

## 10. Fallback
The production system should retain a deterministic rule-based
risk mechanism as a fallback if the ML model is unavailable.
"""

print(ai_documentation)

with open('/content/AI_DOCUMENTATION.md', 'w') as f:
    f.write(ai_documentation)

print("Documentation created successfully!")

from google.colab import files

files.download('/content/AI_DOCUMENTATION.md')

prediction_code = '''
import json
import joblib
import pandas as pd

# Load model
model = joblib.load("rul_random_forest.pkl")

# Load features
with open("features.json", "r") as f:
    features = json.load(f)


def predict_asset(sensor_data):

    # Convert input to DataFrame
    data = pd.DataFrame([sensor_data])

    # Make sure all required features exist
    missing_features = [f for f in features if f not in data.columns]

    if missing_features:
        raise ValueError(
            f"Missing features: {missing_features}"
        )

    # Predict RUL
    predicted_rul = model.predict(data[features])[0]

    # Convert RUL to risk
    if predicted_rul <= 20:
        risk = "High"
        reason = "Very low estimated remaining useful life"

    elif predicted_rul <= 50:
        risk = "Medium"
        reason = "Low estimated remaining useful life"

    else:
        risk = "Low"
        reason = "Sufficient estimated remaining useful life"

    return {
        "predicted_rul": round(float(predicted_rul), 2),
        "risk": risk,
        "reason": reason
    }
'''

with open('/content/prediction.py', 'w') as f:
    f.write(prediction_code)

print("prediction.py created successfully!")

from google.colab import files

files.download('/content/prediction.py')

import sys
sys.path.append('/content')

from prediction import predict_asset

sample_data = {
    'sensor1': test_raw['sensor1'].iloc[0],
    'sensor2': test_raw['sensor2'].iloc[0],
    'sensor3': test_raw['sensor3'].iloc[0],
    'sensor4': test_raw['sensor4'].iloc[0],
    'sensor5': test_raw['sensor5'].iloc[0],
    'sensor6': test_raw['sensor6'].iloc[0],
    'sensor7': test_raw['sensor7'].iloc[0],
    'sensor8': test_raw['sensor8'].iloc[0],
    'sensor9': test_raw['sensor9'].iloc[0],
    'sensor10': test_raw['sensor10'].iloc[0],
    'sensor11': test_raw['sensor11'].iloc[0],
    'sensor12': test_raw['sensor12'].iloc[0],
    'sensor13': test_raw['sensor13'].iloc[0],
    'sensor14': test_raw['sensor14'].iloc[0],
    'sensor15': test_raw['sensor15'].iloc[0],
    'sensor16': test_raw['sensor16'].iloc[0],
    'sensor17': test_raw['sensor17'].iloc[0],
    'sensor18': test_raw['sensor18'].iloc[0],
    'sensor19': test_raw['sensor19'].iloc[0],
    'sensor20': test_raw['sensor20'].iloc[0],
    'sensor21': test_raw['sensor21'].iloc[0]
}

result = predict_asset(sample_data)

print(result)

import os

print(os.listdir())

import zipfile
import os

zip_path = "/content/tables.zip"
extract_path = "/content/tables_data"

with zipfile.ZipFile(zip_path, "r") as zip_ref:
    zip_ref.extractall(extract_path)

print("Files:")
for root, dirs, files in os.walk(extract_path):
    for file in files:
        print(os.path.join(root, file))

import os

print(os.listdir("/content"))

import os

for root, dirs, files in os.walk("/content/tables_data"):
    print("Folder:", root)
    for file in files:
        print("  ", file)

import pandas as pd

assets = pd.read_csv("/content/tables_data/tables/assets.csv")
events = pd.read_csv("/content/tables_data/tables/asset_events.csv")
work_orders = pd.read_csv("/content/tables_data/tables/work_orders.csv")

print("=== ASSETS ===")
print(assets.columns.tolist())

print("\n=== ASSET EVENTS ===")
print(events.columns.tolist())

print("\n=== WORK ORDERS ===")
print(work_orders.columns.tolist())

print("=== WORK ORDER OUTCOMES ===")
print(work_orders["outcome"].value_counts(dropna=False))

print("\n=== EVENT TYPES ===")
print(events["event_type"].value_counts(dropna=False))

print("=== COMPLETION NOTES ===")
print(work_orders["completion_notes"].dropna().head(30).to_string(index=False))

print("\n=== EVENT DATA ===")
print(events["event_data"].dropna().head(30).to_string(index=False))

# Identify corrective/fault-related work orders
corrective_mask = (
    work_orders["completion_notes"]
    .fillna("")
    .str.contains("corrective job|fault report", case=False, regex=True)
)

corrective_orders = work_orders[corrective_mask].copy()

print("Number of corrective/fault-related work orders:",
      len(corrective_orders))

print("\nDates:")
print(
    corrective_orders[
        ["asset_id", "scheduled_at", "started_at", "completed_at",
         "outcome", "completion_notes"]
    ].head(20).to_string(index=False)
)

print("Earliest work order:", work_orders["scheduled_at"].min())
print("Latest work order:", work_orders["scheduled_at"].max())

print("Number of assets:", assets["id"].nunique())
print("Number of corrective assets:", corrective_orders["asset_id"].nunique())

print("\nCorrective jobs by year:")
print(
    pd.to_datetime(corrective_orders["scheduled_at"])
    .dt.year
    .value_counts()
    .sort_index()
)

import pandas as pd

# Convert dates
corrective_orders["scheduled_at"] = pd.to_datetime(
    corrective_orders["scheduled_at"],
    utc=True
)

# Keep only the information needed for the failure-event timeline
failure_events = (
    corrective_orders[["asset_id", "scheduled_at"]]
    .dropna()
    .sort_values(["asset_id", "scheduled_at"])
    .reset_index(drop=True)
)

print("Failure events:", len(failure_events))
print("Assets with failures:", failure_events["asset_id"].nunique())

print("\nFirst 10 failure events:")
print(failure_events.head(10).to_string(index=False))

# Create 30/60/90-day failure labels for each asset's historical work-order date

# All work-order dates available in the dataset
all_work_order_dates = pd.to_datetime(
    work_orders["scheduled_at"],
    utc=True,
    errors="coerce"
).dropna()

dataset_end = all_work_order_dates.max()

print("Dataset end:", dataset_end)

def has_future_failure(asset_id, prediction_date, days):
    future_failures = failure_events[
        (failure_events["asset_id"] == asset_id) &
        (failure_events["scheduled_at"] > prediction_date) &
        (failure_events["scheduled_at"] <= prediction_date + pd.Timedelta(days=days))
    ]
    return int(len(future_failures) > 0)

# Use work-order dates as prediction points
prediction_points = (
    work_orders[["asset_id", "scheduled_at"]]
    .copy()
)

prediction_points["scheduled_at"] = pd.to_datetime(
    prediction_points["scheduled_at"],
    utc=True,
    errors="coerce"
)

prediction_points = prediction_points.dropna(
    subset=["asset_id", "scheduled_at"]
).drop_duplicates()

# Remove points too close to the end of the dataset.
# Otherwise, we could incorrectly label them as "no future failure"
# simply because the data stops.
max_horizon = 90
prediction_points = prediction_points[
    prediction_points["scheduled_at"] <=
    dataset_end - pd.Timedelta(days=max_horizon)
].copy()

print("Prediction points:", len(prediction_points))

prediction_points["failure_30d"] = prediction_points.apply(
    lambda row: has_future_failure(
        row["asset_id"], row["scheduled_at"], 30
    ),
    axis=1
)

prediction_points["failure_60d"] = prediction_points.apply(
    lambda row: has_future_failure(
        row["asset_id"], row["scheduled_at"], 60
    ),
    axis=1
)

prediction_points["failure_90d"] = prediction_points.apply(
    lambda row: has_future_failure(
        row["asset_id"], row["scheduled_at"], 90
    ),
    axis=1
)

print("\nLabel counts:")
print(prediction_points[
    ["failure_30d", "failure_60d", "failure_90d"]
].sum())

print("\nLabel percentages:")
print(
    prediction_points[
        ["failure_30d", "failure_60d", "failure_90d"]
    ].mean().mul(100).round(2)
)

import pandas as pd
import numpy as np

# Make copies so we don't modify the original data
wo = work_orders.copy()
ast = assets.copy()

# Convert dates
date_cols = [
    "scheduled_at",
    "started_at",
    "completed_at",
    "created_at",
    "updated_at"
]

for col in date_cols:
    wo[col] = pd.to_datetime(wo[col], utc=True, errors="coerce")

ast["purchase_date"] = pd.to_datetime(
    ast["purchase_date"], utc=True, errors="coerce"
)

ast["next_maintenance_due_at"] = pd.to_datetime(
    ast["next_maintenance_due_at"], utc=True, errors="coerce"
)

# Mark corrective/fault-related work orders
wo["is_corrective"] = (
    wo["completion_notes"]
    .fillna("")
    .str.contains(
        "corrective job|fault report",
        case=False,
        regex=True
    )
).astype(int)

# Make sure numeric columns are numeric
wo["downtime_minutes"] = pd.to_numeric(
    wo["downtime_minutes"],
    errors="coerce"
).fillna(0)

wo["parts_cost"] = pd.to_numeric(
    wo["parts_cost"],
    errors="coerce"
).fillna(0)

wo["labor_cost"] = pd.to_numeric(
    wo["labor_cost"],
    errors="coerce"
).fillna(0)

wo["total_cost"] = wo["parts_cost"] + wo["labor_cost"]

# Prediction points
feature_data = prediction_points.copy()

feature_data["prediction_date"] = pd.to_datetime(
    feature_data["scheduled_at"],
    utc=True,
    errors="coerce"
)

# Sort for easier historical calculations
wo = wo.sort_values("scheduled_at")

def create_features(row):
    asset_id = row["asset_id"]
    prediction_date = row["prediction_date"]

    # ONLY use work orders BEFORE prediction date
    history = wo[
        (wo["asset_id"] == asset_id) &
        (wo["scheduled_at"] < prediction_date)
    ]

    # Asset information
    asset_row = ast[ast["id"] == asset_id]

    if len(asset_row) > 0:
        asset_row = asset_row.iloc[0]
        purchase_date = asset_row["purchase_date"]
        next_due = asset_row["next_maintenance_due_at"]
    else:
        purchase_date = pd.NaT
        next_due = pd.NaT

    # Asset age in days
    if pd.notna(purchase_date):
        asset_age_days = (
            prediction_date - purchase_date
        ).total_seconds() / 86400
        asset_age_days = max(asset_age_days, 0)
    else:
        asset_age_days = 0

    # Days until next scheduled maintenance
    if pd.notna(next_due):
        days_to_maintenance = (
            next_due - prediction_date
        ).total_seconds() / 86400
    else:
        days_to_maintenance = 9999

    return pd.Series({
        "asset_age_days": asset_age_days,
        "days_to_maintenance": days_to_maintenance,

        # Historical maintenance behavior
        "previous_work_orders": len(history),
        "previous_corrective_jobs": history["is_corrective"].sum(),

        # Historical cost
        "previous_total_cost": history["total_cost"].sum(),

        # Historical downtime
        "previous_downtime_minutes": history["downtime_minutes"].sum(),

        # Recent activity
        "work_orders_last_90d": (
            history["scheduled_at"] >=
            prediction_date - pd.Timedelta(days=90)
        ).sum(),

        "corrective_jobs_last_90d": (
            (
                history["scheduled_at"] >=
                prediction_date - pd.Timedelta(days=90)
            ) &
            (history["is_corrective"] == 1)
        ).sum()
    })


# Create features
features_df = feature_data.apply(create_features, axis=1)

# Combine features with labels
model_data = pd.concat(
    [
        feature_data.reset_index(drop=True),
        features_df.reset_index(drop=True)
    ],
    axis=1
)

print("Feature dataset shape:", model_data.shape)

print("\nFeatures:")
print(features_df.columns.tolist())

print("\nSample:")
print(
    model_data[
        [
            "asset_id",
            "prediction_date",
            "asset_age_days",
            "days_to_maintenance",
            "previous_work_orders",
            "previous_corrective_jobs",
            "previous_total_cost",
            "previous_downtime_minutes",
            "work_orders_last_90d",
            "corrective_jobs_last_90d",
            "failure_30d",
            "failure_60d",
            "failure_90d"
        ]
    ].head().to_string(index=False)
)

print("Dataset shape:", model_data.shape)

for horizon in [30, 60, 90]:
    col = f"failure_{horizon}d"

    positives = int(model_data[col].sum())
    negatives = int((model_data[col] == 0).sum())
    total = len(model_data)

    print(f"\n--- {horizon} days ---")
    print("Positive:", positives)
    print("Negative:", negatives)
    print("Positive rate:", round(positives / total * 100, 2), "%")

from sklearn.model_selection import train_test_split

# Sort chronologically
model_data = model_data.sort_values("prediction_date").reset_index(drop=True)

# Features
feature_cols = [
    "asset_age_days",
    "days_to_maintenance",
    "previous_work_orders",
    "previous_corrective_jobs",
    "previous_total_cost",
    "previous_downtime_minutes",
    "work_orders_last_90d",
    "corrective_jobs_last_90d"
]

X = model_data[feature_cols].copy()
y = model_data["failure_90d"].astype(int)

# Time-based 80/20 split
split_index = int(len(model_data) * 0.80)

X_train = X.iloc[:split_index].copy()
X_test = X.iloc[split_index:].copy()

y_train = y.iloc[:split_index].copy()
y_test = y.iloc[split_index:].copy()

print("Training samples:", len(X_train))
print("Test samples:", len(X_test))

print("\nTraining positives:", y_train.sum())
print("Training negatives:", (y_train == 0).sum())

print("\nTest positives:", y_test.sum())
print("Test negatives:", (y_test == 0).sum())

print("\nTraining period:")
print(model_data.iloc[0]["prediction_date"], "→",
      model_data.iloc[split_index - 1]["prediction_date"])

print("\nTest period:")
print(model_data.iloc[split_index]["prediction_date"], "→",
      model_data.iloc[-1]["prediction_date"])

# Last observed corrective/failure event
last_failure_date = failure_events["scheduled_at"].max()

# We need 90 days after a prediction point to observe the label
evaluation_end = (
    last_failure_date - pd.Timedelta(days=90)
)

print("Last observed failure:")
print(last_failure_date)

print("\nLatest valid prediction date for 90-day labeling:")
print(evaluation_end)

# Keep only prediction points for which a full 90-day future window
# exists inside the observed failure history
valid_model_data = model_data[
    model_data["prediction_date"] <= evaluation_end
].copy()

valid_model_data = (
    valid_model_data
    .sort_values("prediction_date")
    .reset_index(drop=True)
)

print("\nValid dataset shape:", valid_model_data.shape)

print("\n90-day positives:",
      valid_model_data["failure_90d"].sum())

print("90-day negatives:",
      (valid_model_data["failure_90d"] == 0).sum())

# Time-based split on the valid historical period
split_index = int(len(valid_model_data) * 0.80)

X = valid_model_data[feature_cols].copy()
y = valid_model_data["failure_90d"].astype(int)

X_train = X.iloc[:split_index].copy()
X_test = X.iloc[split_index:].copy()

y_train = y.iloc[:split_index].copy()
y_test = y.iloc[split_index:].copy()

print("\n--- Time-based split ---")
print("Training samples:", len(X_train))
print("Test samples:", len(X_test))

print("\nTraining positives:", y_train.sum())
print("Training negatives:", (y_train == 0).sum())

print("\nTest positives:", y_test.sum())
print("Test negatives:", (y_test == 0).sum())

print("\nTraining period:")
print(
    valid_model_data.iloc[0]["prediction_date"],
    "→",
    valid_model_data.iloc[split_index - 1]["prediction_date"]
)

print("\nTest period:")
print(
    valid_model_data.iloc[split_index]["prediction_date"],
    "→",
    valid_model_data.iloc[-1]["prediction_date"]
)

from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

# Logistic Regression pipeline
logistic_90 = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler()),
    ("model", LogisticRegression(
        class_weight="balanced",
        max_iter=1000,
        random_state=42
    ))
])

# Train
logistic_90.fit(X_train, y_train)

# Predict probabilities
y_prob = logistic_90.predict_proba(X_test)[:, 1]

# Default threshold
threshold = 0.5
y_pred = (y_prob >= threshold).astype(int)

print("Model trained successfully.")

print("\nPredicted positive cases:", y_pred.sum())
print("Actual positive cases:", y_test.sum())

print("\nPredicted probabilities:")
print(y_prob)

from sklearn.metrics import (
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

precision = precision_score(
    y_test,
    y_pred,
    zero_division=0
)

recall = recall_score(
    y_test,
    y_pred,
    zero_division=0
)

f1 = f1_score(
    y_test,
    y_pred,
    zero_division=0
)

cm = confusion_matrix(y_test, y_pred)

print("=== 90-Day Logistic Regression ===")

print("\nPrecision:", round(precision, 4))
print("Recall:", round(recall, 4))
print("F1:", round(f1, 4))

print("\nConfusion Matrix:")
print(cm)

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_pred,
        target_names=["No failure", "Failure"],
        zero_division=0
    )
)

tn, fp, fn, tp = cm.ravel()

print("\nDetailed counts:")
print("True Negatives :", tn)
print("False Positives:", fp)
print("False Negatives:", fn)
print("True Positives :", tp)

# Deterministic baseline:
# Predict failure within 90 days if the asset had
# at least one corrective/fault-related job in the previous 90 days.

baseline_pred = (
    valid_model_data["corrective_jobs_last_90d"] > 0
).astype(int)

baseline_precision = precision_score(
    valid_model_data["failure_90d"],
    baseline_pred,
    zero_division=0
)

baseline_recall = recall_score(
    valid_model_data["failure_90d"],
    baseline_pred,
    zero_division=0
)

baseline_f1 = f1_score(
    valid_model_data["failure_90d"],
    baseline_pred,
    zero_division=0
)

baseline_cm = confusion_matrix(
    valid_model_data["failure_90d"],
    baseline_pred
)

print("=== Deterministic 90-Day Baseline ===")

print("\nPrecision:", round(baseline_precision, 4))
print("Recall:", round(baseline_recall, 4))
print("F1:", round(baseline_f1, 4))

print("\nConfusion Matrix:")
print(baseline_cm)

tn, fp, fn, tp = baseline_cm.ravel()

print("\nDetailed counts:")
print("True Negatives :", tn)
print("False Positives:", fp)
print("False Negatives:", fn)
print("True Positives :", tp)

# Deterministic baseline based on maintenance due-date proximity.
# Predict failure within 90 days when maintenance is due within 90 days.

baseline_due_90 = (
    valid_model_data["days_to_maintenance"].between(0, 90)
).astype(int)

baseline_precision = precision_score(
    valid_model_data["failure_90d"],
    baseline_due_90,
    zero_division=0
)

baseline_recall = recall_score(
    valid_model_data["failure_90d"],
    baseline_due_90,
    zero_division=0
)

baseline_f1 = f1_score(
    valid_model_data["failure_90d"],
    baseline_due_90,
    zero_division=0
)

baseline_cm = confusion_matrix(
    valid_model_data["failure_90d"],
    baseline_due_90
)

print("=== Due-Date 90-Day Baseline ===")

print("\nPredicted positives:", baseline_due_90.sum())

print("Precision:", round(baseline_precision, 4))
print("Recall:", round(baseline_recall, 4))
print("F1:", round(baseline_f1, 4))

print("\nConfusion Matrix:")
print(baseline_cm)

tn, fp, fn, tp = baseline_cm.ravel()

print("\nDetailed counts:")
print("True Negatives :", tn)
print("False Positives:", fp)
print("False Negatives:", fn)
print("True Positives :", tp)

thresholds = [0.30, 0.40, 0.50, 0.60, 0.70, 0.80]

threshold_results = []

for threshold in thresholds:

    predictions = (
        y_prob >= threshold
    ).astype(int)

    precision = precision_score(
        y_test,
        predictions,
        zero_division=0
    )

    recall = recall_score(
        y_test,
        predictions,
        zero_division=0
    )

    f1 = f1_score(
        y_test,
        predictions,
        zero_division=0
    )

    tn, fp, fn, tp = confusion_matrix(
        y_test,
        predictions
    ).ravel()

    threshold_results.append({
        "threshold": threshold,
        "precision": round(precision, 4),
        "recall": round(recall, 4),
        "f1": round(f1, 4),
        "false_positives": fp,
        "false_negatives": fn,
        "true_positives": tp
    })

threshold_df = pd.DataFrame(threshold_results)

print(threshold_df.to_string(index=False))

horizons = [30, 60]

valid_datasets = {}

for horizon in horizons:

    # Last date at which we can still observe a full future horizon
    last_failure_date = failure_events["scheduled_at"].max()
    evaluation_end = (
        last_failure_date -
        pd.Timedelta(days=horizon)
    )

    valid_df = model_data[
        model_data["prediction_date"] <= evaluation_end
    ].copy()

    valid_df = (
        valid_df
        .sort_values("prediction_date")
        .reset_index(drop=True)
    )

    valid_datasets[horizon] = valid_df

    positives = int(valid_df[f"failure_{horizon}d"].sum())
    negatives = int(
        (valid_df[f"failure_{horizon}d"] == 0).sum()
    )

    print(f"\n===== {horizon}-DAY DATASET =====")
    print("Evaluation end:", evaluation_end)
    print("Dataset size:", len(valid_df))
    print("Positive failures:", positives)
    print("Negative cases:", negatives)
    print(
        "Positive rate:",
        round(positives / len(valid_df) * 100, 2),
        "%"
    )

from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix

results = {}

for horizon in [30, 60]:

    df = valid_datasets[horizon].copy()

    # Chronological 80/20 split
    split_idx = int(len(df) * 0.8)

    train_df = df.iloc[:split_idx].copy()
    test_df = df.iloc[split_idx:].copy()

    feature_cols = [
        "asset_age_days",
        "days_to_maintenance",
        "previous_work_orders",
        "previous_corrective_jobs",
        "previous_total_cost",
        "previous_downtime_minutes",
        "work_orders_last_90d",
        "corrective_jobs_last_90d"
    ]

    X_train = train_df[feature_cols]
    y_train = train_df[f"failure_{horizon}d"]

    X_test = test_df[feature_cols]
    y_test = test_df[f"failure_{horizon}d"]

    print(f"\n{'='*15} {horizon}-DAY {'='*15}")
    print("Train:", len(train_df), "rows")
    print("Train positives:", int(y_train.sum()))
    print("Test:", len(test_df), "rows")
    print("Test positives:", int(y_test.sum()))

    # Logistic Regression
    model = Pipeline([
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler()),
        ("model", LogisticRegression(
            class_weight="balanced",
            max_iter=1000,
            random_state=42
        ))
    ])

    # Train the model
    model.fit(X_train, y_train)

    # Predict probabilities
    y_prob = model.predict_proba(X_test)[:, 1]

    # Use a default threshold of 0.5 for evaluation
    threshold = 0.5
    y_pred = (y_prob >= threshold).astype(int)

    # Calculate metrics
    precision = precision_score(
        y_test,
        y_pred,
        zero_division=0
    )

    recall = recall_score(
        y_test,
        y_pred,
        zero_division=0
    )

    f1 = f1_score(
        y_test,
        y_pred,
        zero_division=0
    )

    cm = confusion_matrix(y_test, y_pred)

    # Store results
    results[horizon] = {
        "precision": precision,
        "recall": recall,
        "f1": f1,
        "confusion_matrix": cm
    }

for horizon in [30, 60]:

    result = results[horizon]

    print(f"\n{'='*15} {horizon}-DAY RESULTS {'='*15}")

    print("Precision:",
          round(result["precision"], 4))

    print("Recall:",
          round(result["recall"], 4))

    print("F1:",
          round(result["f1"], 4))

    print("\nConfusion Matrix:")
    print(result["confusion_matrix"])

    cm = result["confusion_matrix"]

    if cm.shape == (2, 2):
        tn, fp, fn, tp = cm.ravel()

        print("\nTN:", tn)
        print("FP:", fp)
        print("FN:", fn)
        print("TP:", tp)

for horizon in [30, 60]:

    result = results[horizon]

    print(f"\n{'='*15} {horizon}-DAY RESULTS {'='*15}")

    print("Precision:",
          round(result["precision"], 4))

    print("Recall:",
          round(result["recall"], 4))

    print("F1:",
          round(result["f1"], 4))

    print("\nConfusion Matrix:")
    print(result["confusion_matrix"])

    cm = result["confusion_matrix"]

    if cm.shape == (2, 2):
        tn, fp, fn, tp = cm.ravel()

        print("\nTN:", tn)
        print("FP:", fp)
        print("FN:", fn)
        print("TP:", tp)

from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix

for horizon in [30, 60, 90]:

    # Use the appropriate dataset for the current horizon
    if horizon == 90:
        df = valid_model_data.copy()
    else:
        df = valid_datasets[horizon].copy()

    print(f"\n{'='*20} {horizon}-DAY {'='*20}")

    # -------------------------
    # Deterministic baseline
    # -------------------------
    baseline_pred = (
        df["days_to_maintenance"]
        .between(0, horizon)
        .astype(int)
    )

    y_true = df[f"failure_{horizon}d"]

    baseline_precision = precision_score(
        y_true, baseline_pred, zero_division=0
    )

    baseline_recall = recall_score(
        y_true, baseline_pred, zero_division=0
    )

    baseline_f1 = f1_score(
        y_true, baseline_pred, zero_division=0
    )

    baseline_cm = confusion_matrix(
        y_true, baseline_pred
    )

    print("\n--- Due-date baseline ---")
    print("Predicted positives:", int(baseline_pred.sum()))
    print("Precision:", round(baseline_precision, 4))
    print("Recall:", round(baseline_recall, 4))
    print("F1:", round(baseline_f1, 4))
    print("Confusion matrix:")
    print(baseline_cm)

    # -------------------------
    # ML model
    # -------------------------
    if horizon == 90:
        ml_precision = 0.05
        ml_recall = 0.3333
        ml_f1 = 0.0870
    else:
        result = results[horizon]
        ml_precision = result["precision"]
        ml_recall = result["recall"]
        ml_f1 = result["f1"]

    print("\n--- Logistic Regression ---")
    print("Precision:", round(ml_precision, 4))
    print("Recall:", round(ml_recall, 4))
    print("F1:", round(ml_f1, 4))

import pandas as pd
import numpy as np

# The 90-day model is stored in the `logistic_90` pipeline
logistic_model = logistic_90.named_steps["model"]

feature_cols = [
    "asset_age_days",
    "days_to_maintenance",
    "previous_work_orders",
    "previous_corrective_jobs",
    "previous_total_cost",
    "previous_downtime_minutes",
    "work_orders_last_90d",
    "corrective_jobs_last_90d"
]

coefficients = logistic_model.coef_[0]

feature_importance_90 = pd.DataFrame({
    "feature": feature_cols,
    "coefficient": coefficients,
    "absolute_coefficient": np.abs(coefficients)
}).sort_values(
    "absolute_coefficient",
    ascending=False
)

print(feature_importance_90.to_string(index=False))

def predict_failure_90(asset_features, threshold=0.5):

    # The 90-day model is stored in the `logistic_90` pipeline
    model = logistic_90.named_steps["model"]

    # Convert input to DataFrame
    input_df = pd.DataFrame([asset_features])

    # Predict probability
    probability = float(
        model.predict_proba(input_df)[0, 1]
    )

    prediction = int(probability >= threshold)

    reasons = []

    # Rule-based explanations
    if asset_features["previous_total_cost"] > 1000:
        reasons.append(
            "High historical maintenance cost"
        )

    if asset_features["previous_downtime_minutes"] > 300:
        reasons.append(
            "High historical downtime"
        )

    if asset_features["asset_age_days"] > 365:
        reasons.append(
            "Older asset"
        )

    if asset_features["work_orders_last_90d"] > 0:
        reasons.append(
            "Recent maintenance activity"
        )

    if asset_features["days_to_maintenance"] <= 90:
        reasons.append(
            "Maintenance due within 90 days"
        )

    if not reasons:
        reasons.append(
            "No strong historical risk indicator"
        )

    return {
        "failure_probability": round(probability, 4),
        "predicted_failure_90d": prediction,
        "risk": (
            "High" if probability >= 0.7
            else "Medium" if probability >= 0.3
            else "Low"
        ),
        "reasons": reasons
    }


# Example using the first test row
# The test data for the 90-day model is in X_test
example_features = X_test.iloc[0][[
    "asset_age_days",
    "days_to_maintenance",
    "previous_work_orders",
    "previous_corrective_jobs",
    "previous_total_cost",
    "previous_downtime_minutes",
    "work_orders_last_90d",
    "corrective_jobs_last_90d"
]].to_dict()

prediction_example = predict_failure_90(example_features)

print(prediction_example)

def predict_failure_90(asset_features, threshold=0.5):

    # The 90-day model is stored in the `logistic_90` pipeline
    model = logistic_90.named_steps["model"]

    # Convert input to DataFrame for the pipeline's scaler and model
    # The pipeline expects a DataFrame with feature names
    input_df = pd.DataFrame([asset_features])

    # Predict probability
    probability = float(
        model.predict_proba(input_df)[0, 1]
    )

    prediction = int(probability >= threshold)

    reasons = []

    # Rule-based explanations
    if asset_features["previous_total_cost"] > 1000:
        reasons.append(
            "High historical maintenance cost"
        )

    if asset_features["previous_downtime_minutes"] > 300:
        reasons.append(
            "High historical downtime"
        )

    if asset_features["asset_age_days"] > 365:
        reasons.append(
            "Older asset"
        )

    if asset_features["work_orders_last_90d"] > 0:
        reasons.append(
            "Recent maintenance activity"
        )

    if asset_features["days_to_maintenance"] <= 90:
        reasons.append(
            "Maintenance due within 90 days"
        )

    if not reasons:
        reasons.append(
            "No strong historical risk indicator"
        )

    return {
        "failure_probability": round(probability, 4),
        "predicted_failure_90d": prediction,
        "risk": (
            "High" if probability >= 0.7
            else "Medium" if probability >= 0.3
            else "Low"
        ),
        "reasons": reasons
    }


# Example using the first test row
# The test data for the 90-day model is in X_test
example_features = X_test.iloc[0].to_dict()

prediction_example = predict_failure_90(example_features)

print(prediction_example)

id="model_based_explanation_90"

def predict_failure_90_explained(asset_features, threshold=0.5):

    model = logistic_90

    feature_cols = [
        "asset_age_days",
        "days_to_maintenance",
        "previous_work_orders",
        "previous_corrective_jobs",
        "previous_total_cost",
        "previous_downtime_minutes",
        "work_orders_last_90d",
        "corrective_jobs_last_90d"
    ]

    # Convert input to DataFrame for the pipeline's scaler and model
    # The pipeline expects a DataFrame with feature names
    input_df = pd.DataFrame([asset_features])

    # Get transformed values (apply imputer and scaler from the pipeline)
    imputer = model.named_steps["imputer"]
    scaler = model.named_steps["scaler"]
    classifier = model.named_steps["model"]

    X_imputed = imputer.transform(input_df[feature_cols])
    X_scaled = scaler.transform(X_imputed)

    probability = float(
        model.predict_proba(input_df)[0, 1]
    )

    prediction = int(probability >= threshold)

    # Actual contribution of each feature
    contributions = X_scaled[0] * classifier.coef_[0]

    contribution_df = pd.DataFrame({
        "feature": feature_cols,
        "contribution": contributions
    })

    contribution_df["abs_contribution"] = (
        contribution_df["contribution"].abs()
    )

    contribution_df = contribution_df.sort_values(
        "abs_contribution",
        ascending=False
    )

    reasons = []

    for _, row in contribution_df.head(3).iterrows():

        feature = row["feature"]
        contribution = row["contribution"]

        if contribution > 0:
            direction = "increased"
        else:
            direction = "decreased"

        readable_names = {
            "asset_age_days": "asset age",
            "days_to_maintenance": "days to maintenance",
            "previous_work_orders": "previous work orders",
            "previous_corrective_jobs": "previous corrective jobs",
            "previous_total_cost": "historical maintenance cost",
            "previous_downtime_minutes": "historical downtime",
            "work_orders_last_90d": "recent work orders",
            "corrective_jobs_last_90d": "recent corrective jobs"
        }

        reasons.append(
            f"{readable_names[feature]} {direction} the model's risk score"
        )

    return {
        "failure_probability": round(probability, 4),
        "predicted_failure_90d": prediction,
        "reasons": reasons,
        "feature_contributions": contribution_df[
            ["feature", "contribution"]
        ].to_dict("records")
    }


prediction_example = predict_failure_90_explained(
    example_features
)

print(prediction_example)

import pandas as pd

# The original code produced a KeyError because `results` dictionary only stores
# evaluation metrics for 30 and 60-day horizons, not the 90-day pipeline itself as a key.
# Instead, we need to use the `valid_model_data` and the `split_index` defined
# for the 90-day evaluation (in cell B3Ktbm7DCF6J) to reconstruct the test_df.

# Retrieve the split_index used for the 90-day model's train/test split.
# This was defined in cell B3Ktbm7DCF6J (variable name `split_index`).
# The `valid_model_data` DataFrame is also available globally.
split_index_90_day = int(len(valid_model_data) * 0.80) # Re-calculate for clarity

# Reconstruct the test_df for the 90-day prediction, corresponding to X_test and y_test
current_test_df = valid_model_data.iloc[split_index_90_day:].copy()

# The global `y_test` and `y_pred` variables already hold the true and predicted
# labels for the 90-day model's test set.
# Ensure y_pred is a Series for consistent indexing with y_test.
current_y_test = y_test.reset_index(drop=True)
current_y_pred = pd.Series(y_pred).reset_index(drop=True)

test_df = current_test_df.reset_index(drop=True)
y_test = current_y_test
y_pred = current_y_pred

# Actual future failure date for each prediction point
failure_dates = []

for _, row in test_df.iterrows():

    asset_id = row["asset_id"]
    prediction_date = row["prediction_date"]

    future_failures = failure_events[
        (failure_events["asset_id"] == asset_id) &
        (failure_events["scheduled_at"] > prediction_date) &
        (failure_events["scheduled_at"] <=
         prediction_date + pd.Timedelta(days=90))
    ]

    if len(future_failures) > 0:
        first_failure = future_failures["scheduled_at"].min()
    else:
        first_failure = pd.NaT

    failure_dates.append(first_failure)

test_df["actual_failure_date"] = failure_dates

# Only true positives
tp_mask = (
    (y_test == 1) &
    (pd.Series(y_pred) == 1)
)

tp_rows = test_df[tp_mask].copy()

if len(tp_rows) > 0:

    tp_rows["lead_time_days"] = (
        tp_rows["actual_failure_date"] -
        tp_rows["prediction_date"]
    ).dt.total_seconds() / 86400

    print("True positives:", len(tp_rows))
    print("\nLead times:")
    print(
        tp_rows[
            ["asset_id", "prediction_date",
             "actual_failure_date", "lead_time_days"]
        ].to_string(index=False)
    )

    print(
        "\nMedian lead time:",
        round(tp_rows["lead_time_days"].median(), 2),
        "days"
    )

else:
    print("No true positives found.")

import joblib
import json
from datetime import datetime, timezone
import pandas as pd
from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix

# The `results` dictionary (populated in cell yR3_IHMiEX8_) originally only contained entries
# for 30-day and 60-day horizons. The 90-day model (`logistic_90`) was trained
# and evaluated separately in cells e-IZtMGyCYg2 and Qy2F2QcaCeou.
# To resolve the `KeyError: 90`, we need to explicitly add the 90-day model's
# results to the `results` dictionary before attempting to use them.

# Retrieve the necessary components for the 90-day model from global scope.
# These variables were created and populated in previous cells like B3Ktbm7DCF6J, e-IZtMGyCYg2, and Qy2F2QcaCeou.

# Model pipeline
model_90 = logistic_90 # The trained pipeline for 90-day prediction

# Base data and split index for the 90-day model
df_90_base = valid_model_data.copy() # Base data for 90-day split (from B3Ktbm7DCF6J)
split_idx_90 = int(len(df_90_base) * 0.8) # Split index for 90-day model (from B3Ktbm7DCF6J)

# Reconstruct training and testing DataFrames
train_df_90 = df_90_base.iloc[:split_idx_90].copy()
test_df_90 = df_90_base.iloc[split_idx_90:].copy()

# Feature columns for the 90-day model
feature_cols = [
    "asset_age_days",
    "days_to_maintenance",
    "previous_work_orders",
    "previous_corrective_jobs",
    "previous_total_cost",
    "previous_downtime_minutes",
    "work_orders_last_90d",
    "corrective_jobs_last_90d"
]

X_train_90 = train_df_90[feature_cols]
y_train_90 = train_df_90["failure_90d"]

X_test_90 = test_df_90[feature_cols]
y_test_90 = test_df_90["failure_90d"]

# Predict probabilities and labels using the pre-trained model
y_prob_90 = model_90.predict_proba(X_test_90)[:, 1]
y_pred_90 = (y_prob_90 >= 0.5).astype(int)

# Metrics from Qy2F2QcaCeou (re-calculated for robustness)
precision_90 = precision_score(y_test_90, y_pred_90, zero_division=0)
recall_90 = recall_score(y_test_90, y_pred_90, zero_division=0)
f1_90 = f1_score(y_test_90, y_pred_90, zero_division=0)
cm_90 = confusion_matrix(y_test_90, y_pred_90)

# Ensure the global `results` dictionary exists (it should from `yR3_IHMiEX8_`)
if 'results' not in globals():
    results = {}

# Add the 90-day model results to the dictionary
results[90] = {
    "model": model_90,
    "train_df": train_df_90,
    "test_df": test_df_90,
    "X_train": X_train_90,
    "y_train": y_train_90,
    "X_test": X_test_90,
    "y_test": y_test_90,
    "y_pred": y_pred_90,
    "precision": precision_90,
    "recall": recall_90,
    "f1": f1_90,
    "confusion_matrix": cm_90
}


# Model
joblib.dump(
    results[90]["model"],
    "failure_classifier_90d.pkl"
)

# Features
classifier_features = [
    "asset_age_days",
    "days_to_maintenance",
    "previous_work_orders",
    "previous_corrective_jobs",
    "previous_total_cost",
    "previous_downtime_minutes",
    "work_orders_last_90d",
    "corrective_jobs_last_90d"
]

with open("failure_classifier_features.json", "w") as f:
    json.dump(classifier_features, f, indent=2)

# Model metadata
metadata = {
    "model_name": "90-day Asset Failure Classifier",
    "model_type": "Logistic Regression",
    "target": "failure_within_90_days",
    "threshold": 0.5,
    "training_samples": len(results[90]["train_df"]),
    "test_samples": len(results[90]["test_df"]),
    "test_positive_cases": int(
        results[90]["y_test"].sum()
    ),
    "precision": round(results[90]["precision"], 4),
    "recall": round(results[90]["recall"], 4),
    "f1": round(results[90]["f1"], 4),
    "failure_label_definition":
        "Future corrective/fault-related work order within 90 days",
    "label_proxy":
        "completion_notes contains 'corrective job' or 'fault report'",
    "status": "experimental",
    "created_at": datetime.now(timezone.utc).isoformat(),
    "limitations": [
        "Small number of observed failure cases",
        "Only 3 positive cases in the 90-day test set",
        "Failure labels are a proxy rather than confirmed failure labels",
        "Synthetic project data limits generalization",
        "Model must not automatically change asset or work-order state"
    ]
}

with open("failure_classifier_90d_metadata.json", "w") as f:
    json.dump(metadata, f, indent=2)

print("Saved successfully:")
print("- failure_classifier_90d.pkl")
print("- failure_classifier_features.json")
print("- failure_classifier_90d_metadata.json")

import os

for filename in [
    "failure_classifier_90d.pkl",
    "failure_classifier_features.json",
    "failure_classifier_90d_metadata.json"
]:
    print(filename, "->", os.path.getsize(filename), "bytes")

import joblib
import json
import numpy as np
import pandas as pd

from fastapi import FastAPI
from pydantic import BaseModel

# -------------------------
# Load RUL model
# -------------------------

rf_model = joblib.load("rul_random_forest.pkl")

with open("features.json", "r") as f:
    rul_features = json.load(f)


# -------------------------
# Load 90-day classifier
# -------------------------

failure_model = joblib.load(
    "failure_classifier_90d.pkl"
)

with open("failure_classifier_features.json", "r") as f:
    failure_features = json.load(f)


print("Models loaded successfully.")
print("RUL features:", len(rul_features))
print("Failure features:", len(failure_features))

class SensorInput(BaseModel):

    sensor1: float
    sensor2: float
    sensor3: float
    sensor4: float
    sensor5: float
    sensor6: float
    sensor7: float
    sensor8: float
    sensor9: float
    sensor10: float
    sensor11: float
    sensor12: float
    sensor13: float
    sensor14: float
    sensor15: float
    sensor16: float
    sensor17: float
    sensor18: float
    sensor19: float
    sensor20: float
    sensor21: float


class FailureInput(BaseModel):

    asset_age_days: float
    days_to_maintenance: float
    previous_work_orders: float
    previous_corrective_jobs: float
    previous_total_cost: float
    previous_downtime_minutes: float
    work_orders_last_90d: float
    corrective_jobs_last_90d: float

app = FastAPI(
    title="Predictive Maintenance AI API",
    version="1.0.0"
)


# -------------------------
# Health check
# -------------------------

@app.get("/health")
def health():

    return {
        "status": "online",
        "service": "Predictive Maintenance AI",
        "models": {
            "rul": "loaded",
            "failure_90d": "loaded"
        }
    }


# -------------------------
# RUL prediction
# -------------------------

@app.post("/predict-rul")
def predict_rul(data: SensorInput):

    sensor_data = data.model_dump()

    X = np.array([
        sensor_data[f]
        for f in rul_features
    ]).reshape(1, -1)

    predicted_rul = float(
        rf_model.predict(X)[0]
    )

    if predicted_rul <= 20:
        risk = "High"
        reason = "Very low estimated remaining useful life"

    elif predicted_rul <= 50:
        risk = "Medium"
        reason = "Moderate estimated remaining useful life"

    else:
        risk = "Low"
        reason = "Sufficient estimated remaining useful life"

    return {
        "model_version": "rul-random-forest-v1",
        "predicted_rul": round(predicted_rul, 2),
        "risk": risk,
        "reason": reason
    }


# -------------------------
# 90-day failure prediction
# -------------------------

@app.post("/predict-failure-90d")
def predict_failure_90d(data: FailureInput):

    try:

        input_data = data.model_dump()

        X = pd.DataFrame(
            [[input_data[f] for f in failure_features]],
            columns=failure_features
        )

        probability = float(
            failure_model.predict_proba(X)[0, 1]
        )

        prediction = int(
            probability >= 0.5
        )

        # Simple risk bands for UI
        if probability >= 0.7:
            risk = "High"
        elif probability >= 0.3:
            risk = "Medium"
        else:
            risk = "Low"

        reasons = []

        if input_data["previous_total_cost"] > 1000:
            reasons.append(
                "High historical maintenance cost"
            )

        if input_data["previous_downtime_minutes"] > 300:
            reasons.append(
                "High historical downtime"
            )

        if input_data["asset_age_days"] > 365:
            reasons.append(
                "Older asset"
            )

        if input_data["work_orders_last_90d"] > 0:
            reasons.append(
                "Recent maintenance activity"
            )

        if input_data["days_to_maintenance"] <= 90:
            reasons.append(
                "Maintenance due within 90 days"
            )

        if not reasons:
            reasons.append(
                "No strong historical risk indicator"
            )

        return {
            "model_version":
                "failure-classifier-90d-v1",

            "failure_probability":
                round(probability, 4),

            "predicted_failure_90d":
                prediction,

            "risk":
                risk,

            "reasons":
                reasons,

            "fallback_used":
                False
        }

    except Exception as e:

        # Deterministic fallback
        days = data.days_to_maintenance

        fallback_prediction = int(
            0 <= days <= 90
        )

        return {
            "model_version":
                "deterministic-due-date-fallback-v1",

            "failure_probability":
                None,

            "predicted_failure_90d":
                fallback_prediction,

            "risk":
                "Medium" if fallback_prediction else "Low",

            "reasons": [
                "ML model unavailable; "
                "using deterministic maintenance-due fallback"
            ],

            "fallback_used":
                True
        }

import nest_asyncio
import uvicorn
import threading
import time

nest_asyncio.apply()

def run_api():
    uvicorn.run(
        app,
        host="0.0.0.0",
        port=8000
    )

api_thread = threading.Thread(
    target=run_api,
    daemon=True
)

api_thread.start()

time.sleep(2)

print("FastAPI server started on port 8000")

import requests

response = requests.get(
    "http://127.0.0.1:8000/health"
)

print(response.status_code)
print(response.json())

{
    "status": "online",
    "service": "Predictive Maintenance AI",
    "models": {
        "rul": "loaded",
        "failure_90d": "loaded"
    }
}

import requests
import json

# Take a real historical prediction point
sample = model_data.iloc[0]

payload = {
    "asset_age_days": float(sample["asset_age_days"]),
    "days_to_maintenance": float(sample["days_to_maintenance"]),
    "previous_work_orders": float(sample["previous_work_orders"]),
    "previous_corrective_jobs": float(sample["previous_corrective_jobs"]),
    "previous_total_cost": float(sample["previous_total_cost"]),
    "previous_downtime_minutes": float(sample["previous_downtime_minutes"]),
    "work_orders_last_90d": float(sample["work_orders_last_90d"]),
    "corrective_jobs_last_90d": float(sample["corrective_jobs_last_90d"])
}

response = requests.post(
    "http://127.0.0.1:8000/predict-failure-90d",
    json=payload
)

print("Status:", response.status_code)
print(json.dumps(response.json(), indent=2))

from pathlib import Path
import shutil

src = Path("/content")
dst = Path("/content/predictive_maintenance_ai")
dst.mkdir(exist_ok=True)

required = [
    "rul_random_forest.pkl",
    "features.json",
    "failure_classifier_90d.pkl",
    "failure_classifier_features.json",
]

for name in required:
    source = src / name

    if not source.exists():
        print("❌ Missing:", name)
    else:
        shutil.copy2(source, dst / name)
        print("✅ Copied:", name)

import zipfile
from pathlib import Path

zip_path = Path("/content/predictive_maintenance_ai_render (1).zip")
extract_path = Path("/content")

with zipfile.ZipFile(zip_path, "r") as zip_ref:
    zip_ref.extractall(extract_path)

print("✅ تم فك الضغط")

from pathlib import Path
import shutil

src = Path("/content")
dst = Path("/content/predictive_maintenance_ai")

model_files = [
    "rul_random_forest.pkl",
    "features.json",
    "failure_classifier_90d.pkl",
    "failure_classifier_features.json"
]

for filename in model_files:
    source = src / filename
    target = dst / filename

    if source.exists():
        shutil.copy2(source, target)
        print("✅ تم نسخ:", filename)
    else:
        print("❌ مش موجود:", filename)

import os

folder = "/content/predictive_maintenance_ai"

print("📁 Files inside folder:\n")

for file in sorted(os.listdir(folder)):
    print(" -", file)

import joblib
import json

folder = "/content/predictive_maintenance_ai"

rul_model = joblib.load(f"{folder}/rul_random_forest.pkl")
failure_model = joblib.load(f"{folder}/failure_classifier_90d.pkl")

with open(f"{folder}/features.json") as f:
    rul_features = json.load(f)

with open(f"{folder}/failure_classifier_features.json") as f:
    failure_features = json.load(f)

print("✅ RUL model loaded")
print("✅ Failure model loaded")
print("RUL features:", len(rul_features))
print("Failure features:", len(failure_features))

import shutil

folder = "/content/predictive_maintenance_ai"

zip_path = shutil.make_archive(
    "/content/predictive_maintenance_ai",
    "zip",
    root_dir="/content",
    base_dir="predictive_maintenance_ai"
)

print("✅ ZIP created:", zip_path)